### ISSUE TITLE
I can't select the actions when loading/importing them

### ISSUE THREAD

**Issue by ecols33** [danielhickman/wiki#1]
![screen shot 2015-05-30 at 6 23 09 pm](https://cloud.githubusercontent.com/assets/12535799/7899815/fd73995a-06f8-11e5-8eff-cdc6d8a01507.png)

(notice how they are greyed/not selectable)

**Comment by danielhickman** [comment]
Did this "Open" dialog box open when you added the Actions window?

Actions can't be opened use the `Ctrl + O` or `File > Open` please see the instructions on the correct repo. (https://github.com/danielhickman/MaterialDesign-ShadeTint#installation)

**Comment by ecols33** [comment]
No this dialog opened when I selected load action like it says in the installation README.md

**Comment by danielhickman** [comment]
These actions are for Adobe Illustrator only. Sorry, photoshop doesn't have
pathfinder I think.
